apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-app
  name: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot-app
    spec:
      containers:
      - image: <your-docker-id>/spring-boot-app
        name: spring-boot-app
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-app
  name: spring-boot-app
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-app
  type: ClusterIP
status:
  loadBalancer: {}
